apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-sshd-docker-builder-01
  name: sshd-docker-builder-01
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-sshd-docker-builder-01
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":22,"dnsName":"sshd-docker-builder-01-nodeport","kind":"NodePort","name":"22tcp01","protocol":"TCP","sourcePort":0}]]'
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-sshd-docker-builder-01
    spec:
      containers:
      - env:
        - name: KUBE_CONFIG
          value: '[copy kube config]'
        - name: PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              key: PUBLIC_KEY
              name: ssh-key
              optional: false
        image: docker.io/opmatrix/sshd-docker-builder
        imagePullPolicy: Always
        name: sshd-docker-builder-01
        ports:
        - containerPort: 22
          name: 22tcp01
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          procMount: Default
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      hostname: docker-builder-01
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:default:sshd-docker-builder-01"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  labels:
    cattle.io/creator: norman
  name: sshd-docker-builder-01-nodeport
  namespace: default
## To create automatic cleanups uncomment the "ownerReferences" section and add the uid of the Deployment
#  ownerReferences:
#    - apiVersion: apps/v1
#      controller: true
#      kind: deployment
#      name: sshd-docker-builder-01
#      uid: #Need to insert the uid from the Deployment
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: 22tcp01
      nodePort: 31122
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-sshd-docker-builder-01
  sessionAffinity: None
  type: NodePort