apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-docker-builder
  labels:
    app.kubernetes.io/name: sshd-docker-builder
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sshd-docker-builder
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sshd-docker-builder
    spec:
      containers:
        - imagePullPolicy: Always
          name: sshd-docker-builder
          image: opmatrix/sshd-docker-builder:9
          ports:
            - name: ssh
              expose: true
              protocol: TCP
              containerPort: 22
              _serviceType: LoadBalancer
              _ipam: dhcp
              _listeningPort: 22
          securityContext:
            runAsRoot: true
            readOnlyRootFilesystem: false
            capabilities: {}
            privileged: true
            allowPrivilegeEscalation: true
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          __active: true
      dnsPolicy: ClusterFirst
      hostNetwork: false
      hostname: sshd-docker-builder
      restartPolicy: Always
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate