apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-docker-builder
  labels:
    app.kubernetes.io/name: sshd-docker-builder
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sshd-docker-builder
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sshd-docker-builder
    spec:
      containers:
        - imagePullPolicy: Always
          name: sshd-docker-builder
          ports:
            - name: ssh
              protocol: TCP
              containerPort: 22
          image: opmatrix/sshd-docker-builder:9
          env:
            - name: SSH_PUB_KEY
              valueFrom:
                secretKeyRef:
                  key: SSH_PUB_KEY
                  name: sshd-docker-builder-keys
                  optional: false
            - name: KUBE_CONFIG
              valueFrom:
                secretKeyRef:
                  key: KUBE_CONFIG
                  name: sshd-docker-builder-keys
                  optional: false
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            readOnlyRootFilesystem: false
            capabilities: {}
            privileged: true
            allowPrivilegeEscalation: true
      dnsPolicy: ClusterFirst
      hostNetwork: false
      hostname: sshd-docker-builder
      restartPolicy: Always
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate